### ISSUE TITLE
App not start on Mac

### ISSUE THREAD

**Issue by EAGBCD** [StefanLobbenmeier/youtube-dl-gui#1] opened 2022-10-15 12:59 UTC
**Describe the bug**
Run app but it does not open

**To Reproduce**
Download and install
Run

**Expected behavior**
It work

**Screenshots**

**Additional info (please complete the following information):**
MacOS 10.13.6
Version 2.4.3

**Additional context**

Last login: Fri Oct 14 23:05:21 on ttys000
Users-MacBook-Pro:~ User$ /Volumes/Open\ Video\ Downloader\ 2.4.3/Open\ Video\ Downloader.app/Contents/MacOS/Open\ Video\ Downloader 
SentryError: Attempted to enable Electron native crash reporter but no DSN was supplied
    at new SentryError (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/utils/dist/error.js:9:28)
    at MainBackend.<anonymous> (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:152:27)
    at step (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:124:57)
    at /Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:113:16)
    at MainBackend._installNativeHandler (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:146:24)
    at new MainBackend (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:66:34)
    at MainClient.BaseClient (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/core/dist/baseclient.js:52:25)
Sentry initialized
(node:34441) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries'
    at Object.readdirSync (fs.js:959:3)
    at Object.e.readdirSync (electron/js2c/asar_bundle.js:5:10198)
    at Filepaths.setPermissions (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Filepaths.js:119:12)
    at Filepaths.generateFilepaths (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Filepaths.js:65:22)
    at Environment.initialize (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Environment.js:35:26)
    at App.<anonymous> (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/main.js:228:15)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:483:12)
(node:34441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:34441) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks.

**Comment by StefanLobbenmeier** [comment] 2022-11-10 16:19
Oh I am sorry - I told you to open an issue in your E-Mail but I never got an E-Mail for this issue. Just started watching this repository, hopefully now I will be informed 😄 GitHub has strange defaults for forks it seems

**Comment by StefanLobbenmeier** [comment] 2022-11-10 16:21
> no such file or directory, scandir '/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries

I think this is the clue on why it did not work. Usually on macOS you are supposed to move the application to your Applications folder first, dont start it directly from the .dmg

**Comment by StefanLobbenmeier** [comment] 2022-11-10 16:34
I was able to reproduce the issue when I do not install:

 ```
   ~  /Volumes/Open\ Video\ Downloader\ 2.4.3/Open\ Video\ Downloader.app/Contents/MacOS/Open\ Video\ Downloader
SentryError: Attempted to enable Electron native crash reporter but no DSN was supplied
    at new SentryError (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/utils/dist/error.js:9:28)
    at MainBackend.<anonymous> (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:152:27)
    at step (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:124:57)
    at /Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:113:16)
    at MainBackend._installNativeHandler (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:146:24)
    at new MainBackend (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/backend.js:66:34)
    at MainClient.BaseClient (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/node_modules/@sentry/electron/node_modules/@sentry/core/dist/baseclient.js:52:25)
Sentry initialized
(node:59540) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries'
    at Object.readdirSync (fs.js:959:3)
    at Object.e.readdirSync (electron/js2c/asar_bundle.js:5:10198)
    at Filepaths.setPermissions (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Filepaths.js:119:12)
    at Filepaths.generateFilepaths (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Filepaths.js:65:22)
    at Environment.initialize (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/modules/Environment.js:35:26)
    at App.<anonymous> (/Volumes/Open Video Downloader 2.4.3/Open Video Downloader.app/Contents/Resources/app.asar/main.js:228:15)
    at App.emit (events.js:315:20)
    at App.EventEmitter.emit (domain.js:483:12)
(node:59540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:59540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please try dragging the app to the applications folder and starting it from there. Let me know if that fixes your issue 😄

**Comment by StefanLobbenmeier** [comment] 2022-11-10 17:47
Actually no sorry, this issue also affects an installed version of the app. Somehow 2.4.3 no longer includes this folder, that was present in 2.4.0:

![image](https://user-images.githubusercontent.com/36509607/201169174-bb44d44a-cf22-40ce-b57a-d5c643cc7989.png)

**Comment by EAGBCD** [comment] 2022-11-10 18:19
Thank for checking back. Guess I should have reached out again myself.

Anyway.

I do install it like that, in the applications folder, and still have the issue I descriped originally. 

I also recall finding some missing folder and trying to add it from the previous version. I had the same error. Unfortunately I don’t remember what folder / files it was.

Please let me know if you figure out a fix, or release a new version. Haha somehow simply downloading youtube videos has so far been a difficult and impossible journey for me,despite my initial thoughts that it would be easy.

Thank you again.

**Comment by StefanLobbenmeier** [comment] 2022-11-10 18:31
I am currently releasing 2.4.5, which should fix the issue. I will also test on my Mac and let you know 😄

**Comment by StefanLobbenmeier** [comment] 2022-11-10 18:35
Would you mind testing with 2.4.5 again? https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.4.5 


It fixed the issue on my Mac

**Comment by EAGBCD** [comment] 2022-11-10 19:33
Thank you. I will when I get home in a few hours and will report back to you here. 

Just to be clear and prepared, all I need to do is download and install like a normal mac application correct? No other thing I have to download or extra steps?

Thank you once again.

**Comment by StefanLobbenmeier** [comment] 2022-11-10 20:19
Right, just download, drag to applications and open it 😄

**Comment by EAGBCD** [comment] 2022-11-10 22:58
I am able to download and open the application and all works on that front. 

However I can not download a youtube video. I get the following error. 

{
  "shortMessage": "Command failed with exit code 127: /Applications/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries/yt-dlp-unix -J --flat-playlist --no-cache-dir --ignore-config --user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 --no-check-certificate --yes-playlist https://www.youtube.com/watch?v=j4qfT2dxU6E",
  "command": "/Applications/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries/yt-dlp-unix -J --flat-playlist --no-cache-dir --ignore-config --user-agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 --no-check-certificate --yes-playlist https://www.youtube.com/watch?v=j4qfT2dxU6E",
  "exitCode": 127,
  "stdout": "",
  "stderr": "env: python3: No such file or directory",
  "failed": true,
  "timedOut": false,
  "isCanceled": false,
  "killed": false
}


Sorry for a bit more trouble, and thanks for your efforts.

**Comment by StefanLobbenmeier** [comment] 2022-11-11 09:00
I see, sorry I thought that one was fixed already. For now I have a manual workaround, which is to download yt-dlp-macos-legacy from https://github.com/yt-dlp/yt-dlp/releases/tag/2022.10.04, rename it to yt-dlp-unix and replace /Applications/Open Video Downloader.app/Contents/Resources/app.asar.unpacked/binaries/yt-dlp-unix with this file 

I will have another look to automate this eventually

**Comment by StefanLobbenmeier** [comment] 2022-11-11 11:21
The second issue you are having is a duplicate of https://github.com/jely2002/youtube-dl-gui/issues/243 btw - so when I fix yours both can be closed

**Comment by EAGBCD** [comment] 2022-11-11 14:03
Thanks I appreciate it. I’ll definitely test it for you and let you know.

That link gives a 404, but maybe becuase i’m trying on my phone?

It will be a bit before I can test it, but thanks again for all the effort.

**Comment by StefanLobbenmeier** [comment] 2022-11-11 14:12
Looks like I need to publish it, otherwise only I can see. New link: https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.4.7

**Comment by EAGBCD** [comment] 2022-11-11 14:15
Yup that link works. Thanks again I’ll report back after I can test it.

**Comment by EAGBCD** [comment] 2022-11-12 18:25
Hey it's all working well now! Thanks for all the effort and help.

**Comment by StefanLobbenmeier** [comment] 2022-11-12 18:32
You’re very welcome 😄 thank you for your patience

**Closed by StefanLobbenmeier** 2022-11-12 18:32 UTC
Labels: bug
